// Generated by Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export interface Database {
  public: {
    Tables: {
      Deck: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          user_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          user_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      Flashcard: {
        Row: {
          id: string;
          english_word: string;
          vietnamese_word: string;
          part_of_speech: string;
          example: string | null;
          memory_status: number;
          deck_id: string;
          last_reviewed: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          english_word: string;
          vietnamese_word: string;
          part_of_speech: string;
          example?: string | null;
          memory_status?: number;
          deck_id: string;
          last_reviewed?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          english_word?: string;
          vietnamese_word?: string;
          part_of_speech?: string;
          example?: string | null;
          memory_status?: number;
          deck_id?: string;
          last_reviewed?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      StudySession: {
        Row: {
          id: string;
          deck_id: string | null;
          user_id: string;
          card_count: number;
          correct_count: number;
          started_at: string;
          ended_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          deck_id?: string | null;
          user_id: string;
          card_count: number;
          correct_count?: number;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          deck_id?: string | null;
          user_id?: string;
          card_count?: number;
          correct_count?: number;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      delete_deck_and_flashcards: {
        Args: {
          deck_id: string;
        };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
